# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgIxorPY3nf0MFEa0xAaNrB3zJATVOH3
"""

import os

open_ai_key = os.getenv("OPENAI_API_KEY", "YOUR_KEY")