# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7-T2St33sjzpGMvh1cxTAihASogxy3V
"""

!pip install langchain_openai

from config import open_ai_key
from langchain_openai import ChatOpenAI
from langchain.agents import initialize_agent
from search_agents.py import get_search_tool
from summarizzer_agents import summarize_sources
from report_agent import save_report
from fetch_content import fetch_page_content
from export_report import export_to_pdf

def main():
    topic = input("Enter research topic: ")

    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3, api_key=OPENAI_API_KEY)
    search_tool = get_search_tool()
    agent = initialize_agent([search_tool], llm, agent="zero-shot-react-description", verbose=False)

    print("\n Searching for relevant sources...")
    search_results = agent.run(f"Find the top 5 articles on {topic} and give me the URLs.")

    print("\n Fetching article content...")
    sources_text = fetch_page_content(search_results)

    print("\n Summarizing research...")
    report = summarize_sources(topic, sources_text)

    md_file = save_report(report)
    pdf_file = export_to_pdf(report)

    print(f"\n Research report saved to:\n- {md_file}\n- {pdf_file}")

if __name__ == "__main__":
    main()

