# -*- coding: utf-8 -*-
"""export_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdlADk7ZdSdB4sz0Ibt_FPN7ADUJKt5T
"""

!pip install reportlab

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

def export_to_pdf(report_text, filename = "outputs/sample_report.pdf"):
  os.makedirs("outputs", exist_ok = True)
  c = canvas.Canvas(filename, pagesize = letter)
  width, height = letter
  y = height - 50
  for line in report_text.split("\n"):
    c.drawString(50, y, line[:100])
    y -= 15
  c.save()
  return filename