# -*- coding: utf-8 -*-
"""fetch_content.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viOYbOlA19SIWumPXAGhWd18BM-bddo6
"""

import requests
from bs4 import BeautifulSoup

def fetch_content(url):
  try:
    res = requests.get(url, timeout = 10)
    soup = BeautifulSoup(res.text, "html.parser")
    paragraphs = [p.get_text() for p in soup.find_all("p")]
    return " ".join(paragraphs[:10])
  except Exception as e:
    return f"Error Fetching {url}: {e}"