# -*- coding: utf-8 -*-
"""report_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZYdDJiN-e2olBsQT4x_UhAz7dzZ4pbw
"""

import os

def save_report(report, filename = "outputs/sample_report.md"):
  os.makedirs("outputs", exists_ok = True)
  with open(filename, "w", encoding = "UTF-8") as f:
    f.write(report)
  return filename