# -*- coding: utf-8 -*-
"""search_agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nj_1XPV8V_7nHxKwr8aR6i4fHytkr-Zi
"""

!pip install langchain_community

from langchain_community.tools import DuckDuckGoSearchRun
from langchain.agents import Tool

def get_search_tool():
  search = DuckDuckGoSearchRun()
  return Tool(
      name = "Web Search",
      func = search.run,
      description = "Wanna search a useful information about a research topic?"
  )