# -*- coding: utf-8 -*-
"""summarizzer_agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYW4VMVekDa4f_RpMLvnoNq82kZb77aL
"""

!pip install langchain_openai

from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate

def summarizer_sources(topic, sources):
  llm = ChatOpenAI(model = 'gpt-4o-mini', temperature = 0.3)

  summary_prompt = PromptTemplate(
      input_variables = ['topic', 'sources'],
      template = (
          "You are a research assistant. Summarize the key findings about {topic} "
            "using the following sources:\n\n{sources}\n\n"
            "Return a structured report with:\n"
            "1. Introduction\n2. Key Findings\n3. Challenges & Opportunities\n4. Conclusion"
      ),
  )


  response = llm.invoke(summary_prompt.format(topic = topic,sources = sources))
  return response.content